### ISSUE TITLE
Finish Dashboard UI

### ISSUE THREAD

**Issue by pauchiner** [formizee/formizee#17]
# Roadmap
- [x] Finish endpoint settings page
- [x] Update Sidebar collapse mode
- [x] Add empty page for workspaces without projects
- [x] Update email templates
- [x] Restrict workspace names to avoid conflict with other pages (api, auth, billing, login)
- [x] Responsive Design
