### ISSUE TITLE
Migrate Service Architecture

### ISSUE THREAD

**Issue by pauchiner** [formizee/formizee#18]
# Proposed Architecture

![Comparation](https://github.com/user-attachments/assets/3a7905c6-1cb4-45ad-a764-00959957f659)

# Why?
- Scalability: this structure ensures that the databases are not overloaded with submissions
- Full edge support: At the moment, Neon database is the top bottleneck of the edge architecture
- Cache Integration: With this architecture we cache a lot of thing!
- Security: Now the data is fully encrypted with AES-GCM and isolated

# Roadmap
When this tasks are done, the api and the vault will be total functional.

## packages/db
- [x] Migrate drizzle driver from postgres to sqlite
- [x] Update main db schemas
- [x] Create shared db schemas for submissions 
- [x] Update the api key schema due to security risks

## tools/local
- [x] Use the sqlite driver instead
- [x] Setup the new services with compose

## apps/vault
- [x] Use the new turso schemas to query submissions
- [x] Use Cloudflare KV to cache frequent data
- [x] Use AES-256 for encryption
- [x] Add support for file uploads
- [x] Add latency metrics
- [x] Trace internal errors and context
- [x] Generate a docker image for local development

## packages/vault
- [x] Typed class for interact with the vault

## apps/api
- [x] Update database schemas
- [x] Update the current implementation of the vault
- [x] Accept forms on the post submission route
- [x] Fix csrf and add rate limiter

## apps/dashboard
- [x] Update database schemas
- [x] Update the current implementation of the vault

## apps/docs
- [x] Update api references documentation
- [x] Update local development documentation

## Github Actions
- [x] Update vault ci to use docker for testing
- [x] Update api ci to use docker for testing
